volumes:
  n8n_vol:
  postgres_vol:

networks:
  postgres_net:

services:
  postgres:
    hostname: postgres
    container_name: n8n-postgres
    image: postgres:16-alpine
    # restart: unless-stopped
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - postgres_net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${PG_USERNAME} -d ${PG_DATABASE}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    # build: ./services/n8n
    image: n8nio/n8n:latest
    container_name: n8n-web
    # restart: unless-stopped
    ports:
      - 5678:5678
    env_file:
      - .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${PG_USERNAME}
      - DB_POSTGRESDB_PASSWORD=${PG_PASSWORD}
    networks:
      - postgres_net
    volumes:
      - n8n_vol:/home/node/.n8n
      - ./services/n8n/credentials:/data/credentials
      - ./services/n8n/workflows:/data/workflows
    depends_on:
      postgres:
        condition: service_healthy