global:
  scrape_interval: 15s
  evaluation_interval: 1m

rule_files:
- rules

scrape_configs:
- job_name: qdrant
  static_configs:
  - targets: [ qdrant:6333 ]

- job_name: prometheus
  static_configs:
  - targets: [ prometheus:9090 ]

- job_name: grafana
  static_configs:
  - targets: [ grafana:3000 ]

- job_name: node
  static_configs:
  - targets: [ exporter:9100 ]
