services:
  postgres:
    container_name: n8n-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    networks:
      - n8n_host_net
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h localhost -U ${PG_USERNAME} -d ${PG_DATABASE}"
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_vol:
