services:
  neo4j:
    image: neo4j:latest
    container_name: n8n-neo4j
    volumes:
        - ./.data/neo4j/logs:/logs
        - ./.data/neo4j/config:/config
        - ./.data/neo4j/data:/data
        - ./.data/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    networks:
      - host_net
    ports:
      - "${NEO4J_PORT:-8474}:7474"
      - "8687:7687"
    restart: always